"use client";
import { useCallback, useEffect, useState } from "react";
import BoostNav from "@/components/BoostNav";
type Order = { id:number; provider_order_id:number|null; service_name:string; category:string; link:string; quantity:number; charge_ngn:number; status:string; start_count:string|null; remains:string|null; refill_supported:boolean; refill_id:string|null; refill_status:string|null; created_at:string };
const auth = () => ({ Authorization: `Bearer ${localStorage.getItem('tn_token') ?? ''}` });
export default function BoostOrders() {
  const [orders,setOrders]=useState<Order[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState<number|null>(null);
  const load=useCallback(async()=>{setError('');try{const r=await fetch('/api/smm/orders',{headers:auth(),cache:'no-store'});const d=await r.json();if(!r.ok||!Array.isArray(d))throw new Error(d.error??'Could not load orders.');setOrders(d);}catch(e){setError(e instanceof Error?e.message:'Could not load orders.');}finally{setLoading(false);}},[]);
  useEffect(()=>{const controller=new AbortController();fetch('/api/smm/orders',{headers:auth(),cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok||!Array.isArray(d))throw new Error(d.error??'Could not load orders.');if(!controller.signal.aborted)setOrders(d)}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Could not load orders.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[]);
  async function action(order:Order, refill=false){setBusy(order.id);setError('');try{const r=await fetch(`/api/smm/order${refill?'':`?id=${order.id}`}`,refill?{method:'POST',headers:{...auth(),'Content-Type':'application/json'},body:JSON.stringify({id:order.id,action:'refill'}),cache:'no-store'}:{headers:auth(),cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error??'Request failed.');await load();}catch(e){setError(e instanceof Error?e.message:'Request failed.')}finally{setBusy(null)}}
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-[var(--text-primary)]">Boost orders</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Track your promotion orders and request eligible refills.</p></div><BoostNav /></div>{error&&<p role="alert" className="rounded-xl bg-red-500/10 p-3 text-sm text-red-500">{error}</p>}<div className="overflow-x-auto rounded-2xl border border-[var(--border-color)] bg-[var(--bg-card)]"><table className="w-full min-w-[850px] text-left text-xs"><thead className="text-[var(--text-secondary)]"><tr className="border-b border-[var(--border-color)]"><th className="p-4">Order</th><th className="p-4">Service</th><th className="p-4">Quantity</th><th className="p-4">Charge</th><th className="p-4">Status</th><th className="p-4">Remains</th><th className="p-4">Actions</th></tr></thead><tbody className="divide-y divide-[var(--border-color)]">{loading?<tr><td colSpan={7} className="p-10 text-center">Loading orders…</td></tr>:orders.length===0?<tr><td colSpan={7} className="p-10 text-center text-[var(--text-secondary)]">No boost orders yet.</td></tr>:orders.map(o=><tr key={o.id}><td className="p-4"><b>#{o.id}</b><br/><span className="text-[var(--text-secondary)]">{new Date(o.created_at).toLocaleString()}</span></td><td className="max-w-[260px] p-4"><b>{o.service_name}</b><br/><a href={o.link} target="_blank" rel="noreferrer" className="block truncate text-green-500">{o.link}</a></td><td className="p-4">{o.quantity.toLocaleString()}</td><td className="p-4 font-semibold text-green-500">₦{o.charge_ngn.toLocaleString('en-NG',{minimumFractionDigits:2})}</td><td className="p-4">{o.status}</td><td className="p-4">{o.remains??'—'}</td><td className="p-4"><div className="flex gap-2"><button disabled={busy===o.id||!o.provider_order_id} onClick={()=>void action(o)} className="rounded-lg border border-[var(--border-color)] px-3 py-2 disabled:opacity-40">Refresh</button>{o.refill_supported&&o.provider_order_id&&<button disabled={busy===o.id||!!o.refill_id} onClick={()=>void action(o,true)} className="rounded-lg border border-green-500/30 px-3 py-2 text-green-500 disabled:opacity-40">{o.refill_id?(o.refill_status??'Refill sent'):'Refill'}</button>}</div></td></tr>)}</tbody></table></div></div>;
}
