"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import BoostNav from "@/components/BoostNav";
import { useAuth } from "@/contexts/AuthContext";

type Service = { service: number; name: string; type: string; category: string; rate: number; min: number; max: number; refill: boolean };
const token = () => localStorage.getItem("tn_token") ?? "";

export default function NewBoostOrder() {
  const [services, setServices] = useState<Service[]>([]), [serviceId, setServiceId] = useState(""), [category, setCategory] = useState(""), [link, setLink] = useState(""), [quantity, setQuantity] = useState("");
  const [loading, setLoading] = useState(true), [submitting, setSubmitting] = useState(false), [error, setError] = useState("");
  const router = useRouter(); const { user, refreshUser } = useAuth();
  useEffect(() => { const controller = new AbortController(); fetch('/api/smm/services', { headers: { Authorization: `Bearer ${token()}` }, cache: 'no-store', signal: controller.signal }).then(async r => { const data = await r.json(); if (!r.ok || !Array.isArray(data)) throw new Error(data.error ?? 'Could not load services.'); setServices(data); }).catch(e => { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : 'Could not load services.'); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, []);
  const categories = useMemo(() => [...new Set(services.map(s => s.category))].sort(), [services]);
  const visible = category ? services.filter(s => s.category === category) : services;
  const service = services.find(s => s.service === Number(serviceId));
  const estimated = service && Number(quantity) > 0 ? service.rate * Number(quantity) / 1000 : 0;
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!service) return; setSubmitting(true); setError(''); try { const key = crypto.randomUUID(); const res = await fetch('/api/smm/orders', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token()}`, 'Idempotency-Key': key }, body: JSON.stringify({ service: service.service, link, quantity: Number(quantity) }), cache: 'no-store' }); const data = await res.json(); if (!res.ok) throw new Error(data.error ?? 'Could not place order.'); await refreshUser(); router.push('/boost-account/orders'); } catch(e) { setError(e instanceof Error ? e.message : 'Could not place order.'); } finally { setSubmitting(false); } }
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-[var(--text-primary)]">Boost account</h1><p className="mt-1 text-sm text-[var(--text-secondary)]">Order social media promotion services using your wallet.</p></div><BoostNav /></div>
    <form onSubmit={submit} className="space-y-4 rounded-2xl border border-[var(--border-color)] bg-[var(--bg-card)] p-5 sm:p-6">
      {error && <p role="alert" className="rounded-xl bg-red-500/10 p-2.5 text-xs text-red-500">{error}</p>}
      <label className="block text-xs text-[var(--text-secondary)]">Category<select value={category} onChange={e => { setCategory(e.target.value); setServiceId(''); }} disabled={loading} className="mt-1.5 w-full rounded-lg border border-[var(--border-color)] bg-[var(--bg-card-inner)] px-3 py-2 text-xs text-[var(--text-primary)]"><option value="">All categories</option>{categories.map(c => <option className="text-xs" key={c}>{c}</option>)}</select></label>
      <label className="block text-xs text-[var(--text-secondary)]">Service<select required value={serviceId} onChange={e => { setServiceId(e.target.value); const selected = services.find(s => s.service === Number(e.target.value)); setQuantity(selected ? String(selected.min) : ''); }} disabled={loading} className="mt-1.5 w-full rounded-lg border border-[var(--border-color)] bg-[var(--bg-card-inner)] px-3 py-2 text-xs text-[var(--text-primary)]"><option value="">{loading ? 'Loading services…' : 'Select a service'}</option>{visible.map(s => <option className="text-xs" key={s.service} value={s.service}>{s.name} — ₦{s.rate.toLocaleString('en-NG')}/1,000</option>)}</select></label>
      {service && <div className="grid grid-cols-2 gap-3 rounded-xl bg-[var(--bg-card-inner)] p-4 text-xs text-[var(--text-secondary)] sm:grid-cols-4"><span>Min<br/><b className="text-[var(--text-primary)]">{service.min.toLocaleString()}</b></span><span>Max<br/><b className="text-[var(--text-primary)]">{service.max.toLocaleString()}</b></span><span>Rate<br/><b className="text-green-500">₦{service.rate.toLocaleString('en-NG')}</b></span><span>Refill<br/><b className="text-[var(--text-primary)]">{service.refill ? 'Available' : 'No'}</b></span></div>}
      <label className="block text-xs text-[var(--text-secondary)]">Public link<input type="url" required value={link} onChange={e => setLink(e.target.value)} placeholder="https://…" className="mt-1.5 w-full rounded-lg border border-[var(--border-color)] bg-[var(--bg-card-inner)] px-3 py-2 text-xs text-[var(--text-primary)] placeholder:text-[11px]" /></label>
      <label className="block text-xs text-[var(--text-secondary)]">Quantity<input type="number" required value={quantity} onChange={e => setQuantity(e.target.value)} min={service?.min} max={service?.max} placeholder="Enter quantity" className="mt-1.5 w-full rounded-lg border border-[var(--border-color)] bg-[var(--bg-card-inner)] px-3 py-2 text-xs text-[var(--text-primary)] placeholder:text-[11px]" /></label>
      <div className="flex flex-wrap items-center justify-between gap-4 border-t border-[var(--border-color)] pt-4"><div className="text-xs text-[var(--text-secondary)]">Estimated charge: <b className="text-base text-green-500">₦{estimated.toLocaleString('en-NG', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</b><br/><span>Wallet: ₦{(user?.wallet_balance ?? 0).toLocaleString('en-NG', { minimumFractionDigits: 2 })}</span></div><button disabled={submitting || !service} className="rounded-lg bg-green-500 px-5 py-2.5 text-xs font-semibold text-white disabled:opacity-50">{submitting ? 'Placing order…' : 'Place order'}</button></div>
    </form></div>;
}
